services:
  traefik:
    # Switching to v2 for better stability with your Docker socket version
    image: traefik:v2.11
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # We pass the version directly into the provider here
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443" # Enable HTTPS port
      - "--providers.file.filename=/etc/traefik/traefik_dynamic.yml" # Load the SSL configx`
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro"

  app:
    build: .
    container_name: fastapi-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.localhost`)"
      - "traefik.http.routers.app.entrypoints=websecure" # use HTTPS
      - "traefik.http.routers.app.tls=true" # Enable TLS
      - "traefik.http.services.app-service.loadbalancer.server.port=8000"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.services.prometheus-service.loadbalancer.server.port=9090"
    restart: always
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana-service.loadbalancer.server.port=3000"
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus